### ISSUE TITLE
פרגון לכונן בסיום אירוע

### ISSUE THREAD

**Issue by bajack** [startach/yedidim-bot#102]
כשכונן מסיים אירוע, יקבל תמונה של גביע, ובנוסף פרגון מתוך "בנק פרגונים".
מצ"ב איפיון.
אדאג לרשימה בהמשך

![image](https://user-images.githubusercontent.com/48878614/55314982-fb8ffa80-5473-11e9-87b1-fdcb25c68757.png)

**Comment by dordots** [comment]
DONE
