### ISSUE TITLE
מעקב אחר אירוע

### ISSUE THREAD

**Issue by bajack** [startach/yedidim-bot#105]
מוקדן יוכל לראות את כל הפעולות שקרו באירוע.
מתי נפתח, מתי הוקפץ ועל ידי מי, מה יצא כונן, במידה והכונן ביטל, מתי נסגר האירוע וכו

![image](https://user-images.githubusercontent.com/48878614/55316497-347d9e80-5477-11e9-8409-39dcfd8789e7.png)

**Comment by dordots** [comment]
DONE
