### ISSUE TITLE
עמודות נוספות בחלון החיפוש באפליקציית המוקדנים

### ISSUE THREAD

**Issue by bajack** [startach/yedidim-bot#111]
לאחר חיפוש אירועים באפליקציית המוקדנים, מוצגים רק הנתונים הבאים: זמן, שם, טלפון ובעיה.
יש צורך שתופיע גם הכתובת.
רצוי שיופיעו בחוץ גם נתונים נוספים, כמו סוג הרכב ושם הכונן.
אולי הדרך הנכונה היא שכל אירוע יוצג בשתי שורות, עם קו מפריד בין האירועים.

**Comment by DvirL** [comment]
Merged in #124
