### ISSUE TITLE
הכנסת לינקים חדשים לאפליקציה?

### ISSUE THREAD

**Issue by bajack** [startach/yedidim-bot#119]
מספר חברות סינון סמארטפונים חסמו את האפליקציה באופן אוטומטי, לאחר שטענו כי נוספו לינקים חדשים בקוד האפליקציה, שלא היו קיימים בזמן הבדיקה.
במידה וכך, אצטרך את רשימת הלינקים.

**Comment by alanrubin** [comment]
אלה הקישורים היום:
https://us-central1-yedidim-production.cloudfunctions.net/loadLatestOpenEvents
https://us-central1-yedidim-production.cloudfunctions.net/saveUserLocation
https://us-central1-yedidim-production.cloudfunctions.net/sendDispatcherTestNotification
https://us-central1-yedidim-production.cloudfunctions.net/sendNotificationBySearchRadius
https://us-central1-yedidim-production.cloudfunctions.net/sendNotificationToRecipient
https://us-central1-yedidim-production.cloudfunctions.net/sendTestNotification
https://us-central1-yedidim-production.cloudfunctions.net/sendVolunteerTestNotification

**Comment by alanrubin** [comment]
יש דברים שפירבס עושה ברקע (עדכון בזמן אמת) שגורם לו להתחבר לשרתים של גוגל שאנחנו לא יודעים את הקישור. בכלליות צריך להיות גישה לכ השרותים של פירבס/גוגל.
