### ISSUE TITLE
כניסה לאירוע מתוך הנוטיפיקציה לוקח זמן רב משמעותית ביחס לכניסה רגילה לאירוע

### ISSUE THREAD

**Issue by bajack** [startach/yedidim-bot#121]
בעת כניסה לאירוע מתוך הנוטיפיציה, עשויות לעבור גם כמה דקות עד שהנתונים מופיעים, בשונה מכניסה דרך האפליקציה עצמה בה זה לוקח שניות ספורות

**Comment by alanrubin** [comment]
התיקונים אחרונים פוטרים את הבעיה הזאת כי כל המידע של האירוע מגיע יחד עם ההתראה, אז אין צורך לחכות לטעינה
