### ISSUE TITLE
פתיחת אירועים מהבוט

### ISSUE THREAD

**Issue by odhh** [startach/yedidim-bot#45]
כיום פתיחת אירועים מהבוט מתבצעת ישר לטבלת האירועים ועקב התכתבויות שלא מסתיימות וכדומה,
יוצא שיש אירועים לא מושלמים בטבלת האירועים.
יש לפתוח טבלה חדשה שהיא עותק של טבלת האירועים ותקרא eventBotTemp ושם יפתחו אירועים מהבוט
ורק לאחר שאירוע מושלם ומאושר ע"י מוקדן - הוא יועבר לטבלת האירועים.

**Comment by ChenRoth** [comment]
למה צריך לפתוח טבלה חדשה ולא להשתמש בסינון מתאים לאירועים מושלמים?

**Comment by yossipik** [comment]
הכוונה לפתור את הבעיה של קריאות לכוננים שהגיעו מהבוט ולא עברו דרך המוקדן
מסתבר שזו הייתה אזעקת שווא...
