### ISSUE TITLE
הוספת לוגים לאפליקצית מוקדנים

### ISSUE THREAD

**Issue by dordots** [startach/yedidim-bot#48]
הוספת לוגים לבקרה על שגיאות
יש להוסיף מודלים לטובת אבסטרקציה בהנחה שהשירות ישתנה בהמשך, יש לבצע האזנה שמתבצעות בצד הלקוח ולנטר אותם בשירות הלוגים.

- [x] Login של USER
- [x] בוצע LOGIN
- [x] LOGIN האם הייתה שגיאת
- [x] יצירת TOKEN של התרעות FIREBASE
- [x] יצירת TOKEN של התרעות FIREBASE כישלון
- [x] פתיחת אירוע דרך מוקדנים
- [x] שינוי אירוע - מה השתנה, מי עשה את השינוי
- [x] התראות שהתקבלו

**Comment by ChenRoth** [comment]
#66

**Comment by dordots** [comment]
Done
