### ISSUE TITLE
מוקדן - יצירת קשר דרך וואצפ

### ISSUE THREAD

**Issue by dordots** [startach/yedidim-bot#70]
יש לאפשר לפתוח שיחת וואצפ בלחיצה על מספר הפלאפון של הכונן שלקח את האירוע.

בלחיצה על מספר הפלאפון של הכונן יש לאפשר או שיחה (פתיחה בחייגן) או שליחת הודעה בוואטצפ.

יש לבחור בין אופציה של הצגת דיאלוג של בחירה בין וואצפ לשיחה או לחילופין יש להציג שני לחצנים שונים, של וואצפ ושל שיחה. (מה שנח יותר)

**Comment by aviramst** [comment]
https://github.com/startach/yedidim-bot/pull/83
