### ISSUE TITLE
SCROLL באג: בחירת סוג אירוע תקול

### ISSUE THREAD

**Issue by dordots** [startach/yedidim-bot#84]
כשפותחים אירוע, הדיפולט מופיע על "הנעה", אבל תת התפריט לא מופיע כך שלא ניתן להתקדם - המעקף כיום: בוחרים משהו אחר מהתפריט (למשל "פנצ'ר") ואז בוחרים שוב הנעה, ואת תת הקטגוריה הרלוונטית.

**Comment by DvirL** [comment]
I crated a PR for this, would love if some one can take a look.
The problem, as i understand it, is only on android devices (as seen in the native-base repo [issue's](https://github.com/GeekyAnts/NativeBase/issues/1105)). I don't have an iphone so I can't be sure, but my solution works on android and seems simple enough.

**Comment by DvirL** [comment]
Merged in #89
