### ISSUE TITLE
באג: סגירת אירועים שמגיעים מהבוט

### ISSUE THREAD

**Issue by dordots** [startach/yedidim-bot#87]
אירועים שמגיעים מהבוט לפעמים לא ניתן לסגור.
הסדר כיום הוא שמוקדן שמעוניין לטפל באירוע, נכנס אליו ולוחץ "טפל". כשהוא מסיים לטפל הוא לוחץ "העבר" כדי להעביר לכוננים, ואז לוחץ על "טופל" כדי לסגור את האירוע.
בנקודה הזאת, לעיתים קרובות האפליקציה קורסת ועושה ריסטרט, ולא ניתן לסגור את האירוע - המעקף: המוקדן פותח את אפליקציית הכוננים, "לוקח" את האירוע ולוחץ על סיום.

**Comment by aviramst** [comment]
@dordots זה קורה בתדירות גבוהה? (קרה בשבוע האחרון?) אפשר לבקש מהמוקדנים שאם זה קורה שוב, שידווחו במקום לעשות את המעקף ואז יהיה אפשר לבדוק את זה?

**Comment by bajack** [comment]
לאחר בירור מסתבר שהתקלה כפי הנראה הסתדרה. תודה רבה.
