### ISSUE TITLE
הגדרת מרחק לקבלת אירוע לפי מיקום

### ISSUE THREAD

**Issue by dordots** [startach/yedidim-bot#92]
לאפשר אופציה של ״קבלת אירוע לפי מיקום״ - ואז אתה מגדיר מרחק של 1 ק״מ, 2 ק״מ, 5 ק״מ, 10 ק״מ (למשל). ככה זה מאוד ברור לכונן למה הוא קיבל את האירוע. וזה דרך אגב שיפור מהמצב שיש היום בקבוצות הוואצפ. כי אני אוכל לקבל אירוע בר״ג אם אני נמצא בת״א למשל.

**Comment by aviramst** [comment]
#99
