### ISSUE TITLE
בעיה בטעינת אירועים

### ISSUE THREAD

**Issue by dordots** [startach/yedidim-bot#93]
כשהאפליקציה פתוחה ברקע הרבה זמן, פעם זה היה גורם לרענון שנמשך המון זמן. כיום, אחרי חצי דקה חוזרת הודעת שגיאה, אבל אז צריך לנסות שוב לרענן. לפעמים רק אחרי 3-4 רענונים (2-3 דקות בעצם) מופיעים האירועים. הפתרון שבוצע טוב אך עדיין יש בעיה. יש לתחקר.

**Comment by bajack** [comment]
בוצע תיקון על ידי אלן, אשר מסתיר את האירועים שלא נטענו במלואם.
דבר זה יוצר בעיה, כאשר כוננים מתלוננים שוב ושוב על כך שלא רואים אירועים שהתקבלו, ולכן לא יוצאים לאירועים האלו, מה שגורם לעיתים לכך שאירוע יכול "להתקע" רק בגלל סיבה טכנית כזו.
יש למצוא פתרון יעיל יותר.

**Comment by alanrubin** [comment]
בוצע תיקון נוסף, החזרנו הצגעה של כל האירועים ובנוסף שולחים את המידע על אירוע בכל התראה.

**Comment by alanrubin** [comment]
התיקון גם מתקן #121
